name: Deploy Ridge Site to Unraid

on:
  push:
    branches:
      - main # Trigger this workflow whenever code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest # GitHub-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to clone your repository

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # Load private key from GitHub secret

      - name: Add SSH Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
        # This step adds your Unraid server's fingerprint to the known_hosts file,
        # preventing SSH from prompting for confirmation during the rsync step.

      - name: Deploy with Rsync
        run: |
          rsync -avz --delete \
            ./ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/mnt/user/my-static-website/html/
        # Explanation of rsync command:
        # -avz: archive mode (preserves permissions, timestamps), verbose output, compress data during transfer
        # --delete: deletes extraneous files from the destination (Unraid) that are not in the source (GitHub repo).
        #           This keeps your Unraid site clean and in sync with your repo.
        # ./ : The source directory - means the current directory (your repo's root on the GitHub runner)
        # ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/mnt/user/my-static-website/html/:
        #   The destination on your Unraid server.
        #   IMPORTANT: Make sure '/mnt/user/my-static-website/html/' is the EXACT path
        #              that your Nginx Docker container's '/var/www/html' volume is mapped to.