name: Deploy Ridge Site to Unraid via Tailscale

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Tailscale
        uses: tailscale/github-action@v3 # Use the official Tailscale GitHub Action
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci-oauth # Apply a tag to this ephemeral GitHub Actions runner node
          # version: latest # Optional: specify a Tailscale client version if needed
          # use-cache: 'true' # Optional: for faster runs

      - name: Deploy with Rsync over Tailscale
        run: |
          # Use rsync over SSH. Tailscale makes the SSH connection work
          # using your Unraid server's Tailscale IP or hostname.
          # You may need to replace 'unraid-tower' with your actual Unraid Tailscale hostname
          # or its Tailscale IP (e.g., 100.x.x.x)
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
            ./ \
            github-deploy@100.78.240.7:/mnt/user/ridge-site/html/
        # Explanation of changes:
        # -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null":
        #   This tells rsync to use SSH and disables strict host key checking.
        #   Since the Tailscale node is ephemeral, its host key isn't consistently in known_hosts.
        #   Tailscale's secure authentication makes this generally safe within the tailnet.
        # github-deploy@unraid-tower:
        #   The user on your Unraid server (github-deploy) and its Tailscale hostname.
        #   Make sure 'unraid-tower' is resolvable by Tailscale's MagicDNS in your tailnet,
        #   or use its Tailscale IP address (e.g., 100.x.x.x).