name: Deploy Ridge Site to Unraid

on:
  push:
    branches:
      - main # Trigger this workflow whenever code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest # GitHub-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to clone your repository

      # Ensure the .ssh directory exists and has correct permissions BEFORE ssh-agent tries to use it
      - name: Create .ssh directory with correct permissions
        run: |
          mkdir -p "$HOME/.ssh"
          chmod 700 "$HOME/.ssh"

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # Load private key from GitHub secret

      - name: Add SSH Host to Known Hosts
        run: |
          # The mkdir -p "$HOME/.ssh" is now handled by the previous step
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> "$HOME/.ssh/known_hosts"
          chmod 600 "$HOME/.ssh/known_hosts"
        # Using "$HOME" instead of "~" is often more robust in shell scripts
        # as it explicitly refers to the HOME environment variable.

      - name: Deploy with Rsync
        run: |
          rsync -avz --delete \
            ./ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/mnt/user/my-static-website/html/